// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.wasm;

@com.google.protobuf.Generated
public interface SharedSnippetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.wasm.SharedSnippet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string snippet = 2;</code>
   * @return The snippet.
   */
  java.lang.String getSnippet();
  /**
   * <code>string snippet = 2;</code>
   * @return The bytes for snippet.
   */
  com.google.protobuf.ByteString
      getSnippetBytes();
}
