// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.wasm;

@com.google.protobuf.Generated
public interface StringLiteralInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.wasm.StringLiteralInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string enclosing_type_name = 2;</code>
   * @return The enclosingTypeName.
   */
  java.lang.String getEnclosingTypeName();
  /**
   * <code>string enclosing_type_name = 2;</code>
   * @return The bytes for enclosingTypeName.
   */
  com.google.protobuf.ByteString
      getEnclosingTypeNameBytes();

  /**
   * <code>string method_name = 3;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>string method_name = 3;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();
}
