// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.wasm;

@com.google.protobuf.Generated
public final class SummaryOuterClass {
  private SummaryOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      SummaryOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_wasm_Summary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_wasm_Summary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_wasm_TypeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_wasm_TypeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_wasm_StringLiteralInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_wasm_StringLiteralInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_wasm_SystemPropertyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_wasm_SystemPropertyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_wasm_SharedSnippet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_wasm_SharedSnippet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEtranspiler/java/com/google/j2cl/transp" +
      "iler/backend/wasm/summary.proto\022\tj2cl.wa" +
      "sm\"\207\004\n\007Summary\022\022\n\ntype_names\030\001 \003(\t\022\"\n\005ty" +
      "pes\030\002 \003(\0132\023.j2cl.wasm.TypeInfo\022\'\n\ninterf" +
      "aces\030\003 \003(\0132\023.j2cl.wasm.TypeInfo\0225\n\017strin" +
      "g_literals\030\004 \003(\0132\034.j2cl.wasm.StringLiter" +
      "alInfo\0228\n\021system_properties\030\005 \003(\0132\035.j2cl" +
      ".wasm.SystemPropertyInfo\022/\n\rtype_snippet" +
      "s\030\006 \003(\0132\030.j2cl.wasm.SharedSnippet\022<\n\032nat" +
      "ive_array_type_snippets\030\007 \003(\0132\030.j2cl.was" +
      "m.SharedSnippet\0221\n\017global_snippets\030\010 \003(\013" +
      "2\030.j2cl.wasm.SharedSnippet\0226\n\024wasm_impor" +
      "t_snippets\030\t \003(\0132\030.j2cl.wasm.SharedSnipp" +
      "et\0224\n\022js_import_snippets\030\n \003(\0132\030.j2cl.wa" +
      "sm.SharedSnippet\022\032\n\022js_import_requires\030\013" +
      " \003(\t\"]\n\010TypeInfo\022\017\n\007type_id\030\001 \001(\005\022\024\n\014ext" +
      "ends_type\030\002 \001(\005\022\030\n\020implements_types\030\003 \003(" +
      "\005\022\020\n\010abstract\030\004 \001(\010\"V\n\021StringLiteralInfo" +
      "\022\017\n\007content\030\001 \001(\t\022\033\n\023enclosing_type_name" +
      "\030\002 \001(\t\022\023\n\013method_name\030\003 \001(\t\"?\n\022SystemPro" +
      "pertyInfo\022\024\n\014property_key\030\001 \001(\t\022\023\n\013is_re" +
      "quired\030\002 \001(\010\"-\n\rSharedSnippet\022\013\n\003key\030\001 \001" +
      "(\t\022\017\n\007snippet\030\002 \001(\tB+\n\'com.google.j2cl.t" +
      "ranspiler.backend.wasmP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_j2cl_wasm_Summary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_j2cl_wasm_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_wasm_Summary_descriptor,
        new java.lang.String[] { "TypeNames", "Types", "Interfaces", "StringLiterals", "SystemProperties", "TypeSnippets", "NativeArrayTypeSnippets", "GlobalSnippets", "WasmImportSnippets", "JsImportSnippets", "JsImportRequires", });
    internal_static_j2cl_wasm_TypeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_j2cl_wasm_TypeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_wasm_TypeInfo_descriptor,
        new java.lang.String[] { "TypeId", "ExtendsType", "ImplementsTypes", "Abstract", });
    internal_static_j2cl_wasm_StringLiteralInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_j2cl_wasm_StringLiteralInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_wasm_StringLiteralInfo_descriptor,
        new java.lang.String[] { "Content", "EnclosingTypeName", "MethodName", });
    internal_static_j2cl_wasm_SystemPropertyInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_j2cl_wasm_SystemPropertyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_wasm_SystemPropertyInfo_descriptor,
        new java.lang.String[] { "PropertyKey", "IsRequired", });
    internal_static_j2cl_wasm_SharedSnippet_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_j2cl_wasm_SharedSnippet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_wasm_SharedSnippet_descriptor,
        new java.lang.String[] { "Key", "Snippet", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
