// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto

package com.google.j2cl.transpiler.backend.wasm;

public interface SummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.Summary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string declared_type_map = 1;</code>
   * @return A list containing the declaredTypeMap.
   */
  java.util.List<java.lang.String>
      getDeclaredTypeMapList();
  /**
   * <code>repeated string declared_type_map = 1;</code>
   * @return The count of declaredTypeMap.
   */
  int getDeclaredTypeMapCount();
  /**
   * <code>repeated string declared_type_map = 1;</code>
   * @param index The index of the element to return.
   * @return The declaredTypeMap at the given index.
   */
  java.lang.String getDeclaredTypeMap(int index);
  /**
   * <code>repeated string declared_type_map = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the declaredTypeMap at the given index.
   */
  com.google.protobuf.ByteString
      getDeclaredTypeMapBytes(int index);

  /**
   * <code>repeated string type_reference_map = 2;</code>
   * @return A list containing the typeReferenceMap.
   */
  java.util.List<java.lang.String>
      getTypeReferenceMapList();
  /**
   * <code>repeated string type_reference_map = 2;</code>
   * @return The count of typeReferenceMap.
   */
  int getTypeReferenceMapCount();
  /**
   * <code>repeated string type_reference_map = 2;</code>
   * @param index The index of the element to return.
   * @return The typeReferenceMap at the given index.
   */
  java.lang.String getTypeReferenceMap(int index);
  /**
   * <code>repeated string type_reference_map = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the typeReferenceMap at the given index.
   */
  com.google.protobuf.ByteString
      getTypeReferenceMapBytes(int index);

  /**
   * <code>repeated .j2cl.TypeHierarchyInfo type = 3;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo> 
      getTypeList();
  /**
   * <code>repeated .j2cl.TypeHierarchyInfo type = 3;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo getType(int index);
  /**
   * <code>repeated .j2cl.TypeHierarchyInfo type = 3;</code>
   */
  int getTypeCount();
  /**
   * <code>repeated .j2cl.TypeHierarchyInfo type = 3;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfoOrBuilder> 
      getTypeOrBuilderList();
  /**
   * <code>repeated .j2cl.TypeHierarchyInfo type = 3;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfoOrBuilder getTypeOrBuilder(
      int index);
}
