// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto

package com.google.j2cl.transpiler.backend.wasm;

public final class SummaryOuterClass {
  private SummaryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_Summary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_j2cl_Summary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_TypeHierarchyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_j2cl_TypeHierarchyInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEtranspiler/java/com/google/j2cl/transp" +
      "iler/backend/wasm/summary.proto\022\004j2cl\"g\n" +
      "\007Summary\022\031\n\021declared_type_map\030\001 \003(\t\022\032\n\022t" +
      "ype_reference_map\030\002 \003(\t\022%\n\004type\030\003 \003(\0132\027." +
      "j2cl.TypeHierarchyInfo\"t\n\021TypeHierarchyI" +
      "nfo\022\030\n\020declared_type_id\030\001 \001(\005\022 \n\030extends" +
      "_declared_type_id\030\002 \001(\005\022#\n\033implements_de" +
      "clared_type_id\030\003 \003(\005B+\n\'com.google.j2cl." +
      "transpiler.backend.wasmP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_j2cl_Summary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_j2cl_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_j2cl_Summary_descriptor,
        new java.lang.String[] { "DeclaredTypeMap", "TypeReferenceMap", "Type", });
    internal_static_j2cl_TypeHierarchyInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_j2cl_TypeHierarchyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_j2cl_TypeHierarchyInfo_descriptor,
        new java.lang.String[] { "DeclaredTypeId", "ExtendsDeclaredTypeId", "ImplementsDeclaredTypeId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
