// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.wasm;

@com.google.protobuf.Generated
public interface SummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.wasm.Summary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string type_names = 1;</code>
   * @return A list containing the typeNames.
   */
  java.util.List<java.lang.String>
      getTypeNamesList();
  /**
   * <code>repeated string type_names = 1;</code>
   * @return The count of typeNames.
   */
  int getTypeNamesCount();
  /**
   * <code>repeated string type_names = 1;</code>
   * @param index The index of the element to return.
   * @return The typeNames at the given index.
   */
  java.lang.String getTypeNames(int index);
  /**
   * <code>repeated string type_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the typeNames at the given index.
   */
  com.google.protobuf.ByteString
      getTypeNamesBytes(int index);

  /**
   * <code>repeated .j2cl.wasm.TypeInfo types = 2;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.TypeInfo> 
      getTypesList();
  /**
   * <code>repeated .j2cl.wasm.TypeInfo types = 2;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.TypeInfo getTypes(int index);
  /**
   * <code>repeated .j2cl.wasm.TypeInfo types = 2;</code>
   */
  int getTypesCount();
  /**
   * <code>repeated .j2cl.wasm.TypeInfo types = 2;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.TypeInfoOrBuilder> 
      getTypesOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.TypeInfo types = 2;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.TypeInfoOrBuilder getTypesOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.TypeInfo interfaces = 3;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.TypeInfo> 
      getInterfacesList();
  /**
   * <code>repeated .j2cl.wasm.TypeInfo interfaces = 3;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.TypeInfo getInterfaces(int index);
  /**
   * <code>repeated .j2cl.wasm.TypeInfo interfaces = 3;</code>
   */
  int getInterfacesCount();
  /**
   * <code>repeated .j2cl.wasm.TypeInfo interfaces = 3;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.TypeInfoOrBuilder> 
      getInterfacesOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.TypeInfo interfaces = 3;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.TypeInfoOrBuilder getInterfacesOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.StringLiteralInfo string_literals = 4;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.StringLiteralInfo> 
      getStringLiteralsList();
  /**
   * <code>repeated .j2cl.wasm.StringLiteralInfo string_literals = 4;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.StringLiteralInfo getStringLiterals(int index);
  /**
   * <code>repeated .j2cl.wasm.StringLiteralInfo string_literals = 4;</code>
   */
  int getStringLiteralsCount();
  /**
   * <code>repeated .j2cl.wasm.StringLiteralInfo string_literals = 4;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.StringLiteralInfoOrBuilder> 
      getStringLiteralsOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.StringLiteralInfo string_literals = 4;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.StringLiteralInfoOrBuilder getStringLiteralsOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.SystemPropertyInfo system_properties = 5;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo> 
      getSystemPropertiesList();
  /**
   * <code>repeated .j2cl.wasm.SystemPropertyInfo system_properties = 5;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo getSystemProperties(int index);
  /**
   * <code>repeated .j2cl.wasm.SystemPropertyInfo system_properties = 5;</code>
   */
  int getSystemPropertiesCount();
  /**
   * <code>repeated .j2cl.wasm.SystemPropertyInfo system_properties = 5;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfoOrBuilder> 
      getSystemPropertiesOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.SystemPropertyInfo system_properties = 5;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfoOrBuilder getSystemPropertiesOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.SharedSnippet type_snippets = 6;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.SharedSnippet> 
      getTypeSnippetsList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet type_snippets = 6;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippet getTypeSnippets(int index);
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet type_snippets = 6;</code>
   */
  int getTypeSnippetsCount();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet type_snippets = 6;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder> 
      getTypeSnippetsOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet type_snippets = 6;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder getTypeSnippetsOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.SharedSnippet native_array_type_snippets = 7;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.SharedSnippet> 
      getNativeArrayTypeSnippetsList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet native_array_type_snippets = 7;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippet getNativeArrayTypeSnippets(int index);
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet native_array_type_snippets = 7;</code>
   */
  int getNativeArrayTypeSnippetsCount();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet native_array_type_snippets = 7;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder> 
      getNativeArrayTypeSnippetsOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet native_array_type_snippets = 7;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder getNativeArrayTypeSnippetsOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.SharedSnippet global_snippets = 8;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.SharedSnippet> 
      getGlobalSnippetsList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet global_snippets = 8;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippet getGlobalSnippets(int index);
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet global_snippets = 8;</code>
   */
  int getGlobalSnippetsCount();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet global_snippets = 8;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder> 
      getGlobalSnippetsOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet global_snippets = 8;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder getGlobalSnippetsOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.SharedSnippet wasm_import_snippets = 9;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.SharedSnippet> 
      getWasmImportSnippetsList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet wasm_import_snippets = 9;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippet getWasmImportSnippets(int index);
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet wasm_import_snippets = 9;</code>
   */
  int getWasmImportSnippetsCount();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet wasm_import_snippets = 9;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder> 
      getWasmImportSnippetsOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet wasm_import_snippets = 9;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder getWasmImportSnippetsOrBuilder(
      int index);

  /**
   * <code>repeated .j2cl.wasm.SharedSnippet js_import_snippets = 10;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.wasm.SharedSnippet> 
      getJsImportSnippetsList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet js_import_snippets = 10;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippet getJsImportSnippets(int index);
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet js_import_snippets = 10;</code>
   */
  int getJsImportSnippetsCount();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet js_import_snippets = 10;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder> 
      getJsImportSnippetsOrBuilderList();
  /**
   * <code>repeated .j2cl.wasm.SharedSnippet js_import_snippets = 10;</code>
   */
  com.google.j2cl.transpiler.backend.wasm.SharedSnippetOrBuilder getJsImportSnippetsOrBuilder(
      int index);

  /**
   * <code>repeated string js_import_requires = 11;</code>
   * @return A list containing the jsImportRequires.
   */
  java.util.List<java.lang.String>
      getJsImportRequiresList();
  /**
   * <code>repeated string js_import_requires = 11;</code>
   * @return The count of jsImportRequires.
   */
  int getJsImportRequiresCount();
  /**
   * <code>repeated string js_import_requires = 11;</code>
   * @param index The index of the element to return.
   * @return The jsImportRequires at the given index.
   */
  java.lang.String getJsImportRequires(int index);
  /**
   * <code>repeated string js_import_requires = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the jsImportRequires at the given index.
   */
  com.google.protobuf.ByteString
      getJsImportRequiresBytes(int index);
}
