// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.wasm;

/**
 * Protobuf type {@code j2cl.wasm.SystemPropertyInfo}
 */
@com.google.protobuf.Generated
public final class SystemPropertyInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:j2cl.wasm.SystemPropertyInfo)
    SystemPropertyInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      SystemPropertyInfo.class.getName());
  }
  // Use SystemPropertyInfo.newBuilder() to construct.
  private SystemPropertyInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SystemPropertyInfo() {
    propertyKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_wasm_SystemPropertyInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_wasm_SystemPropertyInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo.class, com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo.Builder.class);
  }

  public static final int PROPERTY_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object propertyKey_ = "";
  /**
   * <code>string property_key = 1;</code>
   * @return The propertyKey.
   */
  @java.lang.Override
  public java.lang.String getPropertyKey() {
    java.lang.Object ref = propertyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      propertyKey_ = s;
      return s;
    }
  }
  /**
   * <code>string property_key = 1;</code>
   * @return The bytes for propertyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPropertyKeyBytes() {
    java.lang.Object ref = propertyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      propertyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IS_REQUIRED_FIELD_NUMBER = 2;
  private boolean isRequired_ = false;
  /**
   * <code>bool is_required = 2;</code>
   * @return The isRequired.
   */
  @java.lang.Override
  public boolean getIsRequired() {
    return isRequired_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(propertyKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, propertyKey_);
    }
    if (isRequired_ != false) {
      output.writeBool(2, isRequired_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(propertyKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, propertyKey_);
    }
    if (isRequired_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isRequired_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo)) {
      return super.equals(obj);
    }
    com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo other = (com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo) obj;

    if (!getPropertyKey()
        .equals(other.getPropertyKey())) return false;
    if (getIsRequired()
        != other.getIsRequired()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROPERTY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getPropertyKey().hashCode();
    hash = (37 * hash) + IS_REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsRequired());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code j2cl.wasm.SystemPropertyInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:j2cl.wasm.SystemPropertyInfo)
      com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_wasm_SystemPropertyInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_wasm_SystemPropertyInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo.class, com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo.Builder.class);
    }

    // Construct using com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      propertyKey_ = "";
      isRequired_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_wasm_SystemPropertyInfo_descriptor;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo getDefaultInstanceForType() {
      return com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo build() {
      com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo buildPartial() {
      com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo result = new com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.propertyKey_ = propertyKey_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isRequired_ = isRequired_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo) {
        return mergeFrom((com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo other) {
      if (other == com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo.getDefaultInstance()) return this;
      if (!other.getPropertyKey().isEmpty()) {
        propertyKey_ = other.propertyKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getIsRequired() != false) {
        setIsRequired(other.getIsRequired());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              propertyKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isRequired_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object propertyKey_ = "";
    /**
     * <code>string property_key = 1;</code>
     * @return The propertyKey.
     */
    public java.lang.String getPropertyKey() {
      java.lang.Object ref = propertyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        propertyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string property_key = 1;</code>
     * @return The bytes for propertyKey.
     */
    public com.google.protobuf.ByteString
        getPropertyKeyBytes() {
      java.lang.Object ref = propertyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        propertyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string property_key = 1;</code>
     * @param value The propertyKey to set.
     * @return This builder for chaining.
     */
    public Builder setPropertyKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      propertyKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string property_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPropertyKey() {
      propertyKey_ = getDefaultInstance().getPropertyKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string property_key = 1;</code>
     * @param value The bytes for propertyKey to set.
     * @return This builder for chaining.
     */
    public Builder setPropertyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      propertyKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean isRequired_ ;
    /**
     * <code>bool is_required = 2;</code>
     * @return The isRequired.
     */
    @java.lang.Override
    public boolean getIsRequired() {
      return isRequired_;
    }
    /**
     * <code>bool is_required = 2;</code>
     * @param value The isRequired to set.
     * @return This builder for chaining.
     */
    public Builder setIsRequired(boolean value) {

      isRequired_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_required = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRequired() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isRequired_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:j2cl.wasm.SystemPropertyInfo)
  }

  // @@protoc_insertion_point(class_scope:j2cl.wasm.SystemPropertyInfo)
  private static final com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo();
  }

  public static com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SystemPropertyInfo>
      PARSER = new com.google.protobuf.AbstractParser<SystemPropertyInfo>() {
    @java.lang.Override
    public SystemPropertyInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SystemPropertyInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SystemPropertyInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.j2cl.transpiler.backend.wasm.SystemPropertyInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

