// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto

package com.google.j2cl.transpiler.backend.wasm;

/**
 * Protobuf type {@code j2cl.TypeHierarchyInfo}
 */
public final class TypeHierarchyInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:j2cl.TypeHierarchyInfo)
    TypeHierarchyInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TypeHierarchyInfo.newBuilder() to construct.
  private TypeHierarchyInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TypeHierarchyInfo() {
    implementsDeclaredTypeId_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TypeHierarchyInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TypeHierarchyInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            declaredTypeId_ = input.readInt32();
            break;
          }
          case 16: {

            extendsDeclaredTypeId_ = input.readInt32();
            break;
          }
          case 24: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              implementsDeclaredTypeId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            implementsDeclaredTypeId_.addInt(input.readInt32());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              implementsDeclaredTypeId_ = newIntList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              implementsDeclaredTypeId_.addInt(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        implementsDeclaredTypeId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_TypeHierarchyInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_TypeHierarchyInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo.class, com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo.Builder.class);
  }

  public static final int DECLARED_TYPE_ID_FIELD_NUMBER = 1;
  private int declaredTypeId_;
  /**
   * <code>int32 declared_type_id = 1;</code>
   * @return The declaredTypeId.
   */
  @java.lang.Override
  public int getDeclaredTypeId() {
    return declaredTypeId_;
  }

  public static final int EXTENDS_DECLARED_TYPE_ID_FIELD_NUMBER = 2;
  private int extendsDeclaredTypeId_;
  /**
   * <code>int32 extends_declared_type_id = 2;</code>
   * @return The extendsDeclaredTypeId.
   */
  @java.lang.Override
  public int getExtendsDeclaredTypeId() {
    return extendsDeclaredTypeId_;
  }

  public static final int IMPLEMENTS_DECLARED_TYPE_ID_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.IntList implementsDeclaredTypeId_;
  /**
   * <code>repeated int32 implements_declared_type_id = 3;</code>
   * @return A list containing the implementsDeclaredTypeId.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getImplementsDeclaredTypeIdList() {
    return implementsDeclaredTypeId_;
  }
  /**
   * <code>repeated int32 implements_declared_type_id = 3;</code>
   * @return The count of implementsDeclaredTypeId.
   */
  public int getImplementsDeclaredTypeIdCount() {
    return implementsDeclaredTypeId_.size();
  }
  /**
   * <code>repeated int32 implements_declared_type_id = 3;</code>
   * @param index The index of the element to return.
   * @return The implementsDeclaredTypeId at the given index.
   */
  public int getImplementsDeclaredTypeId(int index) {
    return implementsDeclaredTypeId_.getInt(index);
  }
  private int implementsDeclaredTypeIdMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (declaredTypeId_ != 0) {
      output.writeInt32(1, declaredTypeId_);
    }
    if (extendsDeclaredTypeId_ != 0) {
      output.writeInt32(2, extendsDeclaredTypeId_);
    }
    if (getImplementsDeclaredTypeIdList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(implementsDeclaredTypeIdMemoizedSerializedSize);
    }
    for (int i = 0; i < implementsDeclaredTypeId_.size(); i++) {
      output.writeInt32NoTag(implementsDeclaredTypeId_.getInt(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (declaredTypeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, declaredTypeId_);
    }
    if (extendsDeclaredTypeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, extendsDeclaredTypeId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < implementsDeclaredTypeId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(implementsDeclaredTypeId_.getInt(i));
      }
      size += dataSize;
      if (!getImplementsDeclaredTypeIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      implementsDeclaredTypeIdMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo)) {
      return super.equals(obj);
    }
    com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo other = (com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo) obj;

    if (getDeclaredTypeId()
        != other.getDeclaredTypeId()) return false;
    if (getExtendsDeclaredTypeId()
        != other.getExtendsDeclaredTypeId()) return false;
    if (!getImplementsDeclaredTypeIdList()
        .equals(other.getImplementsDeclaredTypeIdList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DECLARED_TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeclaredTypeId();
    hash = (37 * hash) + EXTENDS_DECLARED_TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getExtendsDeclaredTypeId();
    if (getImplementsDeclaredTypeIdCount() > 0) {
      hash = (37 * hash) + IMPLEMENTS_DECLARED_TYPE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getImplementsDeclaredTypeIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code j2cl.TypeHierarchyInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:j2cl.TypeHierarchyInfo)
      com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_TypeHierarchyInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_TypeHierarchyInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo.class, com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo.Builder.class);
    }

    // Construct using com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      declaredTypeId_ = 0;

      extendsDeclaredTypeId_ = 0;

      implementsDeclaredTypeId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.j2cl.transpiler.backend.wasm.SummaryOuterClass.internal_static_j2cl_TypeHierarchyInfo_descriptor;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo getDefaultInstanceForType() {
      return com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo build() {
      com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo buildPartial() {
      com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo result = new com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo(this);
      int from_bitField0_ = bitField0_;
      result.declaredTypeId_ = declaredTypeId_;
      result.extendsDeclaredTypeId_ = extendsDeclaredTypeId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        implementsDeclaredTypeId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.implementsDeclaredTypeId_ = implementsDeclaredTypeId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo) {
        return mergeFrom((com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo other) {
      if (other == com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo.getDefaultInstance()) return this;
      if (other.getDeclaredTypeId() != 0) {
        setDeclaredTypeId(other.getDeclaredTypeId());
      }
      if (other.getExtendsDeclaredTypeId() != 0) {
        setExtendsDeclaredTypeId(other.getExtendsDeclaredTypeId());
      }
      if (!other.implementsDeclaredTypeId_.isEmpty()) {
        if (implementsDeclaredTypeId_.isEmpty()) {
          implementsDeclaredTypeId_ = other.implementsDeclaredTypeId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureImplementsDeclaredTypeIdIsMutable();
          implementsDeclaredTypeId_.addAll(other.implementsDeclaredTypeId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int declaredTypeId_ ;
    /**
     * <code>int32 declared_type_id = 1;</code>
     * @return The declaredTypeId.
     */
    @java.lang.Override
    public int getDeclaredTypeId() {
      return declaredTypeId_;
    }
    /**
     * <code>int32 declared_type_id = 1;</code>
     * @param value The declaredTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setDeclaredTypeId(int value) {
      
      declaredTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 declared_type_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeclaredTypeId() {
      
      declaredTypeId_ = 0;
      onChanged();
      return this;
    }

    private int extendsDeclaredTypeId_ ;
    /**
     * <code>int32 extends_declared_type_id = 2;</code>
     * @return The extendsDeclaredTypeId.
     */
    @java.lang.Override
    public int getExtendsDeclaredTypeId() {
      return extendsDeclaredTypeId_;
    }
    /**
     * <code>int32 extends_declared_type_id = 2;</code>
     * @param value The extendsDeclaredTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setExtendsDeclaredTypeId(int value) {
      
      extendsDeclaredTypeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 extends_declared_type_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtendsDeclaredTypeId() {
      
      extendsDeclaredTypeId_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList implementsDeclaredTypeId_ = emptyIntList();
    private void ensureImplementsDeclaredTypeIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        implementsDeclaredTypeId_ = mutableCopy(implementsDeclaredTypeId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated int32 implements_declared_type_id = 3;</code>
     * @return A list containing the implementsDeclaredTypeId.
     */
    public java.util.List<java.lang.Integer>
        getImplementsDeclaredTypeIdList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(implementsDeclaredTypeId_) : implementsDeclaredTypeId_;
    }
    /**
     * <code>repeated int32 implements_declared_type_id = 3;</code>
     * @return The count of implementsDeclaredTypeId.
     */
    public int getImplementsDeclaredTypeIdCount() {
      return implementsDeclaredTypeId_.size();
    }
    /**
     * <code>repeated int32 implements_declared_type_id = 3;</code>
     * @param index The index of the element to return.
     * @return The implementsDeclaredTypeId at the given index.
     */
    public int getImplementsDeclaredTypeId(int index) {
      return implementsDeclaredTypeId_.getInt(index);
    }
    /**
     * <code>repeated int32 implements_declared_type_id = 3;</code>
     * @param index The index to set the value at.
     * @param value The implementsDeclaredTypeId to set.
     * @return This builder for chaining.
     */
    public Builder setImplementsDeclaredTypeId(
        int index, int value) {
      ensureImplementsDeclaredTypeIdIsMutable();
      implementsDeclaredTypeId_.setInt(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 implements_declared_type_id = 3;</code>
     * @param value The implementsDeclaredTypeId to add.
     * @return This builder for chaining.
     */
    public Builder addImplementsDeclaredTypeId(int value) {
      ensureImplementsDeclaredTypeIdIsMutable();
      implementsDeclaredTypeId_.addInt(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 implements_declared_type_id = 3;</code>
     * @param values The implementsDeclaredTypeId to add.
     * @return This builder for chaining.
     */
    public Builder addAllImplementsDeclaredTypeId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureImplementsDeclaredTypeIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, implementsDeclaredTypeId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 implements_declared_type_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplementsDeclaredTypeId() {
      implementsDeclaredTypeId_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:j2cl.TypeHierarchyInfo)
  }

  // @@protoc_insertion_point(class_scope:j2cl.TypeHierarchyInfo)
  private static final com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo();
  }

  public static com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TypeHierarchyInfo>
      PARSER = new com.google.protobuf.AbstractParser<TypeHierarchyInfo>() {
    @java.lang.Override
    public TypeHierarchyInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TypeHierarchyInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TypeHierarchyInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TypeHierarchyInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.j2cl.transpiler.backend.wasm.TypeHierarchyInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

