// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto

package com.google.j2cl.transpiler.backend.wasm;

public interface TypeHierarchyInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.TypeHierarchyInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 declared_type_id = 1;</code>
   * @return The declaredTypeId.
   */
  int getDeclaredTypeId();

  /**
   * <code>int32 extends_declared_type_id = 2;</code>
   * @return The extendsDeclaredTypeId.
   */
  int getExtendsDeclaredTypeId();

  /**
   * <code>repeated int32 implements_declared_type_id = 3;</code>
   * @return A list containing the implementsDeclaredTypeId.
   */
  java.util.List<java.lang.Integer> getImplementsDeclaredTypeIdList();
  /**
   * <code>repeated int32 implements_declared_type_id = 3;</code>
   * @return The count of implementsDeclaredTypeId.
   */
  int getImplementsDeclaredTypeIdCount();
  /**
   * <code>repeated int32 implements_declared_type_id = 3;</code>
   * @param index The index of the element to return.
   * @return The implementsDeclaredTypeId at the given index.
   */
  int getImplementsDeclaredTypeId(int index);
}
