// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/wasm/summary.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.wasm;

@com.google.protobuf.Generated
public interface TypeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.wasm.TypeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type_id = 1;</code>
   * @return The typeId.
   */
  int getTypeId();

  /**
   * <code>int32 extends_type = 2;</code>
   * @return The extendsType.
   */
  int getExtendsType();

  /**
   * <code>repeated int32 implements_types = 3;</code>
   * @return A list containing the implementsTypes.
   */
  java.util.List<java.lang.Integer> getImplementsTypesList();
  /**
   * <code>repeated int32 implements_types = 3;</code>
   * @return The count of implementsTypes.
   */
  int getImplementsTypesCount();
  /**
   * <code>repeated int32 implements_types = 3;</code>
   * @param index The index of the element to return.
   * @return The implementsTypes at the given index.
   */
  int getImplementsTypes(int index);

  /**
   * <code>bool abstract = 4;</code>
   * @return The abstract.
   */
  boolean getAbstract();
}
