// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.libraryinfo;

@com.google.protobuf.Generated
public interface LibraryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.LibraryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string type_names = 1;</code>
   * @return A list containing the typeNames.
   */
  java.util.List<java.lang.String>
      getTypeNamesList();
  /**
   * <code>repeated string type_names = 1;</code>
   * @return The count of typeNames.
   */
  int getTypeNamesCount();
  /**
   * <code>repeated string type_names = 1;</code>
   * @param index The index of the element to return.
   * @return The typeNames at the given index.
   */
  java.lang.String getTypeNames(int index);
  /**
   * <code>repeated string type_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the typeNames at the given index.
   */
  com.google.protobuf.ByteString
      getTypeNamesBytes(int index);

  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> 
      getTypesList();
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getTypes(int index);
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  int getTypesCount();
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
      getTypesOrBuilderList();
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder getTypesOrBuilder(
      int index);
}
