// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto

package com.google.j2cl.transpiler.backend.libraryinfo;

public interface LibraryInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.LibraryInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string type_map = 1;</code>
   * @return A list containing the typeMap.
   */
  java.util.List<java.lang.String>
      getTypeMapList();
  /**
   * <code>repeated string type_map = 1;</code>
   * @return The count of typeMap.
   */
  int getTypeMapCount();
  /**
   * <code>repeated string type_map = 1;</code>
   * @param index The index of the element to return.
   * @return The typeMap at the given index.
   */
  java.lang.String getTypeMap(int index);
  /**
   * <code>repeated string type_map = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the typeMap at the given index.
   */
  com.google.protobuf.ByteString
      getTypeMapBytes(int index);

  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> 
      getTypeList();
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getType(int index);
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  int getTypeCount();
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
      getTypeOrBuilderList();
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder getTypeOrBuilder(
      int index);
}
