// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.libraryinfo;

@com.google.protobuf.Generated
public final class LibraryInfoOuterClass {
  private LibraryInfoOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      LibraryInfoOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_LibraryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_LibraryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_TypeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_TypeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_MemberInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_MemberInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_MethodInvocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_MethodInvocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_SourcePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_j2cl_SourcePosition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nQtranspiler/java/com/google/j2cl/transp" +
      "iler/backend/libraryinfo/library_info.pr" +
      "oto\022\004j2cl\"@\n\013LibraryInfo\022\022\n\ntype_names\030\001" +
      " \003(\t\022\035\n\005types\030\002 \003(\0132\016.j2cl.TypeInfo\"\310\001\n\010" +
      "TypeInfo\022\017\n\007type_id\030\001 \001(\005\022\024\n\014extends_typ" +
      "e\030\002 \001(\005\022\030\n\020implements_types\030\003 \003(\005\022!\n\007mem" +
      "bers\030\004 \003(\0132\020.j2cl.MemberInfo\022\037\n\027header_s" +
      "ource_file_path\030\005 \001(\t\022\035\n\025impl_source_fil" +
      "e_path\030\006 \001(\t\022\030\n\020jstype_interface\030\007 \001(\010\"\264" +
      "\001\n\nMemberInfo\022\014\n\004name\030\001 \001(\t\022\016\n\006static\030\003 " +
      "\001(\010\022\025\n\rjs_accessible\030\004 \001(\010\022/\n\017invoked_me" +
      "thods\030\005 \003(\0132\026.j2cl.MethodInvocation\022\030\n\020r" +
      "eferenced_types\030\006 \003(\005\022&\n\010position\030\007 \001(\0132" +
      "\024.j2cl.SourcePosition\":\n\020MethodInvocatio" +
      "n\022\016\n\006method\030\001 \001(\t\022\026\n\016enclosing_type\030\002 \001(" +
      "\005\",\n\016SourcePosition\022\r\n\005start\030\001 \001(\005\022\013\n\003en" +
      "d\030\002 \001(\005B2\n.com.google.j2cl.transpiler.ba" +
      "ckend.libraryinfoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_j2cl_LibraryInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_j2cl_LibraryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_LibraryInfo_descriptor,
        new java.lang.String[] { "TypeNames", "Types", });
    internal_static_j2cl_TypeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_j2cl_TypeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_TypeInfo_descriptor,
        new java.lang.String[] { "TypeId", "ExtendsType", "ImplementsTypes", "Members", "HeaderSourceFilePath", "ImplSourceFilePath", "JstypeInterface", });
    internal_static_j2cl_MemberInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_j2cl_MemberInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_MemberInfo_descriptor,
        new java.lang.String[] { "Name", "Static", "JsAccessible", "InvokedMethods", "ReferencedTypes", "Position", });
    internal_static_j2cl_MethodInvocation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_j2cl_MethodInvocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_MethodInvocation_descriptor,
        new java.lang.String[] { "Method", "EnclosingType", });
    internal_static_j2cl_SourcePosition_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_j2cl_SourcePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_j2cl_SourcePosition_descriptor,
        new java.lang.String[] { "Start", "End", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
