// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto

package com.google.j2cl.transpiler.backend.libraryinfo;

public final class LibraryInfoOuterClass {
  private LibraryInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_LibraryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_j2cl_LibraryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_TypeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_j2cl_TypeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_MemberInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_j2cl_MemberInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_MethodInvocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_j2cl_MethodInvocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_j2cl_SourcePosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_j2cl_SourcePosition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nQtranspiler/java/com/google/j2cl/transp" +
      "iler/backend/libraryinfo/library_info.pr" +
      "oto\022\004j2cl\"=\n\013LibraryInfo\022\020\n\010type_map\030\001 \003" +
      "(\t\022\034\n\004type\030\002 \003(\0132\016.j2cl.TypeInfo\"\306\001\n\010Typ" +
      "eInfo\022\017\n\007type_id\030\001 \001(\005\022\024\n\014extends_type\030\002" +
      " \001(\005\022\027\n\017implements_type\030\003 \003(\005\022 \n\006member\030" +
      "\004 \003(\0132\020.j2cl.MemberInfo\022\037\n\027header_source" +
      "_file_path\030\005 \001(\t\022\035\n\025impl_source_file_pat" +
      "h\030\006 \001(\t\022\030\n\020jstype_interface\030\007 \001(\010\"\264\001\n\nMe" +
      "mberInfo\022\014\n\004name\030\001 \001(\t\022\016\n\006static\030\003 \001(\010\022\025" +
      "\n\rjs_accessible\030\004 \001(\010\022/\n\017invoked_methods" +
      "\030\005 \003(\0132\026.j2cl.MethodInvocation\022\030\n\020refere" +
      "nced_types\030\006 \003(\005\022&\n\010position\030\007 \001(\0132\024.j2c" +
      "l.SourcePosition\":\n\020MethodInvocation\022\016\n\006" +
      "method\030\001 \001(\t\022\026\n\016enclosing_type\030\002 \001(\005\",\n\016" +
      "SourcePosition\022\r\n\005start\030\001 \001(\005\022\013\n\003end\030\002 \001" +
      "(\005B2\n.com.google.j2cl.transpiler.backend" +
      ".libraryinfoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_j2cl_LibraryInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_j2cl_LibraryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_j2cl_LibraryInfo_descriptor,
        new java.lang.String[] { "TypeMap", "Type", });
    internal_static_j2cl_TypeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_j2cl_TypeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_j2cl_TypeInfo_descriptor,
        new java.lang.String[] { "TypeId", "ExtendsType", "ImplementsType", "Member", "HeaderSourceFilePath", "ImplSourceFilePath", "JstypeInterface", });
    internal_static_j2cl_MemberInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_j2cl_MemberInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_j2cl_MemberInfo_descriptor,
        new java.lang.String[] { "Name", "Static", "JsAccessible", "InvokedMethods", "ReferencedTypes", "Position", });
    internal_static_j2cl_MethodInvocation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_j2cl_MethodInvocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_j2cl_MethodInvocation_descriptor,
        new java.lang.String[] { "Method", "EnclosingType", });
    internal_static_j2cl_SourcePosition_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_j2cl_SourcePosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_j2cl_SourcePosition_descriptor,
        new java.lang.String[] { "Start", "End", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
