// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.libraryinfo;

/**
 * Protobuf type {@code j2cl.LibraryInfo}
 */
@com.google.protobuf.Generated
public final class LibraryInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:j2cl.LibraryInfo)
    LibraryInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      LibraryInfo.class.getName());
  }
  // Use LibraryInfo.newBuilder() to construct.
  private LibraryInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private LibraryInfo() {
    typeNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    types_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.Builder.class);
  }

  public static final int TYPE_NAMES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList typeNames_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string type_names = 1;</code>
   * @return A list containing the typeNames.
   */
  public com.google.protobuf.ProtocolStringList
      getTypeNamesList() {
    return typeNames_;
  }
  /**
   * <code>repeated string type_names = 1;</code>
   * @return The count of typeNames.
   */
  public int getTypeNamesCount() {
    return typeNames_.size();
  }
  /**
   * <code>repeated string type_names = 1;</code>
   * @param index The index of the element to return.
   * @return The typeNames at the given index.
   */
  public java.lang.String getTypeNames(int index) {
    return typeNames_.get(index);
  }
  /**
   * <code>repeated string type_names = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the typeNames at the given index.
   */
  public com.google.protobuf.ByteString
      getTypeNamesBytes(int index) {
    return typeNames_.getByteString(index);
  }

  public static final int TYPES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> types_;
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> getTypesList() {
    return types_;
  }
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
      getTypesOrBuilderList() {
    return types_;
  }
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  @java.lang.Override
  public int getTypesCount() {
    return types_.size();
  }
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getTypes(int index) {
    return types_.get(index);
  }
  /**
   * <code>repeated .j2cl.TypeInfo types = 2;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder getTypesOrBuilder(
      int index) {
    return types_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < typeNames_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, typeNames_.getRaw(i));
    }
    for (int i = 0; i < types_.size(); i++) {
      output.writeMessage(2, types_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < typeNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(typeNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTypeNamesList().size();
    }
    for (int i = 0; i < types_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, types_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo)) {
      return super.equals(obj);
    }
    com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo other = (com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo) obj;

    if (!getTypeNamesList()
        .equals(other.getTypeNamesList())) return false;
    if (!getTypesList()
        .equals(other.getTypesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTypeNamesCount() > 0) {
      hash = (37 * hash) + TYPE_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getTypeNamesList().hashCode();
    }
    if (getTypesCount() > 0) {
      hash = (37 * hash) + TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getTypesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code j2cl.LibraryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:j2cl.LibraryInfo)
      com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.Builder.class);
    }

    // Construct using com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      typeNames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      if (typesBuilder_ == null) {
        types_ = java.util.Collections.emptyList();
      } else {
        types_ = null;
        typesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_descriptor;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo getDefaultInstanceForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo build() {
      com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo buildPartial() {
      com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo result = new com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo result) {
      if (typesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          types_ = java.util.Collections.unmodifiableList(types_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.types_ = types_;
      } else {
        result.types_ = typesBuilder_.build();
      }
    }

    private void buildPartial0(com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        typeNames_.makeImmutable();
        result.typeNames_ = typeNames_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo) {
        return mergeFrom((com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo other) {
      if (other == com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.getDefaultInstance()) return this;
      if (!other.typeNames_.isEmpty()) {
        if (typeNames_.isEmpty()) {
          typeNames_ = other.typeNames_;
          bitField0_ |= 0x00000001;
        } else {
          ensureTypeNamesIsMutable();
          typeNames_.addAll(other.typeNames_);
        }
        onChanged();
      }
      if (typesBuilder_ == null) {
        if (!other.types_.isEmpty()) {
          if (types_.isEmpty()) {
            types_ = other.types_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTypesIsMutable();
            types_.addAll(other.types_);
          }
          onChanged();
        }
      } else {
        if (!other.types_.isEmpty()) {
          if (typesBuilder_.isEmpty()) {
            typesBuilder_.dispose();
            typesBuilder_ = null;
            types_ = other.types_;
            bitField0_ = (bitField0_ & ~0x00000002);
            typesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetTypesFieldBuilder() : null;
          } else {
            typesBuilder_.addAllMessages(other.types_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTypeNamesIsMutable();
              typeNames_.add(s);
              break;
            } // case 10
            case 18: {
              com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo m =
                  input.readMessage(
                      com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.parser(),
                      extensionRegistry);
              if (typesBuilder_ == null) {
                ensureTypesIsMutable();
                types_.add(m);
              } else {
                typesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList typeNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTypeNamesIsMutable() {
      if (!typeNames_.isModifiable()) {
        typeNames_ = new com.google.protobuf.LazyStringArrayList(typeNames_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @return A list containing the typeNames.
     */
    public com.google.protobuf.ProtocolStringList
        getTypeNamesList() {
      typeNames_.makeImmutable();
      return typeNames_;
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @return The count of typeNames.
     */
    public int getTypeNamesCount() {
      return typeNames_.size();
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @param index The index of the element to return.
     * @return The typeNames at the given index.
     */
    public java.lang.String getTypeNames(int index) {
      return typeNames_.get(index);
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the typeNames at the given index.
     */
    public com.google.protobuf.ByteString
        getTypeNamesBytes(int index) {
      return typeNames_.getByteString(index);
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @param index The index to set the value at.
     * @param value The typeNames to set.
     * @return This builder for chaining.
     */
    public Builder setTypeNames(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTypeNamesIsMutable();
      typeNames_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @param value The typeNames to add.
     * @return This builder for chaining.
     */
    public Builder addTypeNames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTypeNamesIsMutable();
      typeNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @param values The typeNames to add.
     * @return This builder for chaining.
     */
    public Builder addAllTypeNames(
        java.lang.Iterable<java.lang.String> values) {
      ensureTypeNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, typeNames_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeNames() {
      typeNames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_names = 1;</code>
     * @param value The bytes of the typeNames to add.
     * @return This builder for chaining.
     */
    public Builder addTypeNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTypeNamesIsMutable();
      typeNames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> types_ =
      java.util.Collections.emptyList();
    private void ensureTypesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        types_ = new java.util.ArrayList<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo>(types_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> typesBuilder_;

    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> getTypesList() {
      if (typesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(types_);
      } else {
        return typesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public int getTypesCount() {
      if (typesBuilder_ == null) {
        return types_.size();
      } else {
        return typesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getTypes(int index) {
      if (typesBuilder_ == null) {
        return types_.get(index);
      } else {
        return typesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder setTypes(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo value) {
      if (typesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.set(index, value);
        onChanged();
      } else {
        typesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder setTypes(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder builderForValue) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.set(index, builderForValue.build());
        onChanged();
      } else {
        typesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder addTypes(com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo value) {
      if (typesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.add(value);
        onChanged();
      } else {
        typesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder addTypes(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo value) {
      if (typesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypesIsMutable();
        types_.add(index, value);
        onChanged();
      } else {
        typesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder addTypes(
        com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder builderForValue) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.add(builderForValue.build());
        onChanged();
      } else {
        typesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder addTypes(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder builderForValue) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.add(index, builderForValue.build());
        onChanged();
      } else {
        typesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder addAllTypes(
        java.lang.Iterable<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> values) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, types_);
        onChanged();
      } else {
        typesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder clearTypes() {
      if (typesBuilder_ == null) {
        types_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        typesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public Builder removeTypes(int index) {
      if (typesBuilder_ == null) {
        ensureTypesIsMutable();
        types_.remove(index);
        onChanged();
      } else {
        typesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder getTypesBuilder(
        int index) {
      return internalGetTypesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder getTypesOrBuilder(
        int index) {
      if (typesBuilder_ == null) {
        return types_.get(index);  } else {
        return typesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
         getTypesOrBuilderList() {
      if (typesBuilder_ != null) {
        return typesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(types_);
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder addTypesBuilder() {
      return internalGetTypesFieldBuilder().addBuilder(
          com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder addTypesBuilder(
        int index) {
      return internalGetTypesFieldBuilder().addBuilder(
          index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.TypeInfo types = 2;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder> 
         getTypesBuilderList() {
      return internalGetTypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
        internalGetTypesFieldBuilder() {
      if (typesBuilder_ == null) {
        typesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder>(
                types_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        types_ = null;
      }
      return typesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:j2cl.LibraryInfo)
  }

  // @@protoc_insertion_point(class_scope:j2cl.LibraryInfo)
  private static final com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo();
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LibraryInfo>
      PARSER = new com.google.protobuf.AbstractParser<LibraryInfo>() {
    @java.lang.Override
    public LibraryInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LibraryInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LibraryInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

