// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto

package com.google.j2cl.transpiler.backend.libraryinfo;

/**
 * Protobuf type {@code j2cl.LibraryInfo}
 */
public final class LibraryInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:j2cl.LibraryInfo)
    LibraryInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LibraryInfo.newBuilder() to construct.
  private LibraryInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LibraryInfo() {
    typeMap_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    type_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LibraryInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LibraryInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              typeMap_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            typeMap_.add(s);
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              type_ = new java.util.ArrayList<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo>();
              mutable_bitField0_ |= 0x00000002;
            }
            type_.add(
                input.readMessage(com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        typeMap_ = typeMap_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        type_ = java.util.Collections.unmodifiableList(type_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.Builder.class);
  }

  public static final int TYPE_MAP_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList typeMap_;
  /**
   * <code>repeated string type_map = 1;</code>
   * @return A list containing the typeMap.
   */
  public com.google.protobuf.ProtocolStringList
      getTypeMapList() {
    return typeMap_;
  }
  /**
   * <code>repeated string type_map = 1;</code>
   * @return The count of typeMap.
   */
  public int getTypeMapCount() {
    return typeMap_.size();
  }
  /**
   * <code>repeated string type_map = 1;</code>
   * @param index The index of the element to return.
   * @return The typeMap at the given index.
   */
  public java.lang.String getTypeMap(int index) {
    return typeMap_.get(index);
  }
  /**
   * <code>repeated string type_map = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the typeMap at the given index.
   */
  public com.google.protobuf.ByteString
      getTypeMapBytes(int index) {
    return typeMap_.getByteString(index);
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> type_;
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> getTypeList() {
    return type_;
  }
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
      getTypeOrBuilderList() {
    return type_;
  }
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  @java.lang.Override
  public int getTypeCount() {
    return type_.size();
  }
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getType(int index) {
    return type_.get(index);
  }
  /**
   * <code>repeated .j2cl.TypeInfo type = 2;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder getTypeOrBuilder(
      int index) {
    return type_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < typeMap_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, typeMap_.getRaw(i));
    }
    for (int i = 0; i < type_.size(); i++) {
      output.writeMessage(2, type_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < typeMap_.size(); i++) {
        dataSize += computeStringSizeNoTag(typeMap_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTypeMapList().size();
    }
    for (int i = 0; i < type_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, type_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo)) {
      return super.equals(obj);
    }
    com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo other = (com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo) obj;

    if (!getTypeMapList()
        .equals(other.getTypeMapList())) return false;
    if (!getTypeList()
        .equals(other.getTypeList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTypeMapCount() > 0) {
      hash = (37 * hash) + TYPE_MAP_FIELD_NUMBER;
      hash = (53 * hash) + getTypeMapList().hashCode();
    }
    if (getTypeCount() > 0) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTypeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code j2cl.LibraryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:j2cl.LibraryInfo)
      com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.Builder.class);
    }

    // Construct using com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTypeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      typeMap_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (typeBuilder_ == null) {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        typeBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_LibraryInfo_descriptor;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo getDefaultInstanceForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo build() {
      com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo buildPartial() {
      com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo result = new com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        typeMap_ = typeMap_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.typeMap_ = typeMap_;
      if (typeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.type_ = type_;
      } else {
        result.type_ = typeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo) {
        return mergeFrom((com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo other) {
      if (other == com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo.getDefaultInstance()) return this;
      if (!other.typeMap_.isEmpty()) {
        if (typeMap_.isEmpty()) {
          typeMap_ = other.typeMap_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTypeMapIsMutable();
          typeMap_.addAll(other.typeMap_);
        }
        onChanged();
      }
      if (typeBuilder_ == null) {
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
      } else {
        if (!other.type_.isEmpty()) {
          if (typeBuilder_.isEmpty()) {
            typeBuilder_.dispose();
            typeBuilder_ = null;
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000002);
            typeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTypeFieldBuilder() : null;
          } else {
            typeBuilder_.addAllMessages(other.type_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList typeMap_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTypeMapIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        typeMap_ = new com.google.protobuf.LazyStringArrayList(typeMap_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @return A list containing the typeMap.
     */
    public com.google.protobuf.ProtocolStringList
        getTypeMapList() {
      return typeMap_.getUnmodifiableView();
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @return The count of typeMap.
     */
    public int getTypeMapCount() {
      return typeMap_.size();
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @param index The index of the element to return.
     * @return The typeMap at the given index.
     */
    public java.lang.String getTypeMap(int index) {
      return typeMap_.get(index);
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the typeMap at the given index.
     */
    public com.google.protobuf.ByteString
        getTypeMapBytes(int index) {
      return typeMap_.getByteString(index);
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @param index The index to set the value at.
     * @param value The typeMap to set.
     * @return This builder for chaining.
     */
    public Builder setTypeMap(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeMapIsMutable();
      typeMap_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @param value The typeMap to add.
     * @return This builder for chaining.
     */
    public Builder addTypeMap(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTypeMapIsMutable();
      typeMap_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @param values The typeMap to add.
     * @return This builder for chaining.
     */
    public Builder addAllTypeMap(
        java.lang.Iterable<java.lang.String> values) {
      ensureTypeMapIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, typeMap_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeMap() {
      typeMap_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string type_map = 1;</code>
     * @param value The bytes of the typeMap to add.
     * @return This builder for chaining.
     */
    public Builder addTypeMapBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTypeMapIsMutable();
      typeMap_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> type_ =
      java.util.Collections.emptyList();
    private void ensureTypeIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        type_ = new java.util.ArrayList<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo>(type_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> typeBuilder_;

    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> getTypeList() {
      if (typeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(type_);
      } else {
        return typeBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public int getTypeCount() {
      if (typeBuilder_ == null) {
        return type_.size();
      } else {
        return typeBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getType(int index) {
      if (typeBuilder_ == null) {
        return type_.get(index);
      } else {
        return typeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder setType(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
      } else {
        typeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder setType(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder builderForValue) {
      if (typeBuilder_ == null) {
        ensureTypeIsMutable();
        type_.set(index, builderForValue.build());
        onChanged();
      } else {
        typeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder addType(com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
      } else {
        typeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder addType(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTypeIsMutable();
        type_.add(index, value);
        onChanged();
      } else {
        typeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder addType(
        com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder builderForValue) {
      if (typeBuilder_ == null) {
        ensureTypeIsMutable();
        type_.add(builderForValue.build());
        onChanged();
      } else {
        typeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder addType(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder builderForValue) {
      if (typeBuilder_ == null) {
        ensureTypeIsMutable();
        type_.add(index, builderForValue.build());
        onChanged();
      } else {
        typeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder addAllType(
        java.lang.Iterable<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo> values) {
      if (typeBuilder_ == null) {
        ensureTypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, type_);
        onChanged();
      } else {
        typeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder clearType() {
      if (typeBuilder_ == null) {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        typeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public Builder removeType(int index) {
      if (typeBuilder_ == null) {
        ensureTypeIsMutable();
        type_.remove(index);
        onChanged();
      } else {
        typeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder getTypeBuilder(
        int index) {
      return getTypeFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder getTypeOrBuilder(
        int index) {
      if (typeBuilder_ == null) {
        return type_.get(index);  } else {
        return typeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
         getTypeOrBuilderList() {
      if (typeBuilder_ != null) {
        return typeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(type_);
      }
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder addTypeBuilder() {
      return getTypeFieldBuilder().addBuilder(
          com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder addTypeBuilder(
        int index) {
      return getTypeFieldBuilder().addBuilder(
          index, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.TypeInfo type = 2;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder> 
         getTypeBuilderList() {
      return getTypeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder> 
        getTypeFieldBuilder() {
      if (typeBuilder_ == null) {
        typeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder>(
                type_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      return typeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:j2cl.LibraryInfo)
  }

  // @@protoc_insertion_point(class_scope:j2cl.LibraryInfo)
  private static final com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo();
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LibraryInfo>
      PARSER = new com.google.protobuf.AbstractParser<LibraryInfo>() {
    @java.lang.Override
    public LibraryInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LibraryInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LibraryInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LibraryInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

