// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.libraryinfo;

/**
 * Protobuf type {@code j2cl.MemberInfo}
 */
@com.google.protobuf.Generated
public final class MemberInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:j2cl.MemberInfo)
    MemberInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      MemberInfo.class.getName());
  }
  // Use MemberInfo.newBuilder() to construct.
  private MemberInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MemberInfo() {
    name_ = "";
    invokedMethods_ = java.util.Collections.emptyList();
    referencedTypes_ = emptyIntList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_MemberInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_MemberInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATIC_FIELD_NUMBER = 3;
  private boolean static_ = false;
  /**
   * <code>bool static = 3;</code>
   * @return The static.
   */
  @java.lang.Override
  public boolean getStatic() {
    return static_;
  }

  public static final int JS_ACCESSIBLE_FIELD_NUMBER = 4;
  private boolean jsAccessible_ = false;
  /**
   * <code>bool js_accessible = 4;</code>
   * @return The jsAccessible.
   */
  @java.lang.Override
  public boolean getJsAccessible() {
    return jsAccessible_;
  }

  public static final int INVOKED_METHODS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation> invokedMethods_;
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation> getInvokedMethodsList() {
    return invokedMethods_;
  }
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder> 
      getInvokedMethodsOrBuilderList() {
    return invokedMethods_;
  }
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  @java.lang.Override
  public int getInvokedMethodsCount() {
    return invokedMethods_.size();
  }
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation getInvokedMethods(int index) {
    return invokedMethods_.get(index);
  }
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder getInvokedMethodsOrBuilder(
      int index) {
    return invokedMethods_.get(index);
  }

  public static final int REFERENCED_TYPES_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList referencedTypes_ =
      emptyIntList();
  /**
   * <code>repeated int32 referenced_types = 6;</code>
   * @return A list containing the referencedTypes.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getReferencedTypesList() {
    return referencedTypes_;
  }
  /**
   * <code>repeated int32 referenced_types = 6;</code>
   * @return The count of referencedTypes.
   */
  public int getReferencedTypesCount() {
    return referencedTypes_.size();
  }
  /**
   * <code>repeated int32 referenced_types = 6;</code>
   * @param index The index of the element to return.
   * @return The referencedTypes at the given index.
   */
  public int getReferencedTypes(int index) {
    return referencedTypes_.getInt(index);
  }
  private int referencedTypesMemoizedSerializedSize = -1;

  public static final int POSITION_FIELD_NUMBER = 7;
  private com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition position_;
  /**
   * <code>.j2cl.SourcePosition position = 7;</code>
   * @return Whether the position field is set.
   */
  @java.lang.Override
  public boolean hasPosition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.j2cl.SourcePosition position = 7;</code>
   * @return The position.
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition getPosition() {
    return position_ == null ? com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.getDefaultInstance() : position_;
  }
  /**
   * <code>.j2cl.SourcePosition position = 7;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.SourcePositionOrBuilder getPositionOrBuilder() {
    return position_ == null ? com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.getDefaultInstance() : position_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (static_ != false) {
      output.writeBool(3, static_);
    }
    if (jsAccessible_ != false) {
      output.writeBool(4, jsAccessible_);
    }
    for (int i = 0; i < invokedMethods_.size(); i++) {
      output.writeMessage(5, invokedMethods_.get(i));
    }
    if (getReferencedTypesList().size() > 0) {
      output.writeUInt32NoTag(50);
      output.writeUInt32NoTag(referencedTypesMemoizedSerializedSize);
    }
    for (int i = 0; i < referencedTypes_.size(); i++) {
      output.writeInt32NoTag(referencedTypes_.getInt(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(7, getPosition());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (static_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, static_);
    }
    if (jsAccessible_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, jsAccessible_);
    }
    for (int i = 0; i < invokedMethods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, invokedMethods_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < referencedTypes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(referencedTypes_.getInt(i));
      }
      size += dataSize;
      if (!getReferencedTypesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      referencedTypesMemoizedSerializedSize = dataSize;
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getPosition());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo)) {
      return super.equals(obj);
    }
    com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo other = (com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getStatic()
        != other.getStatic()) return false;
    if (getJsAccessible()
        != other.getJsAccessible()) return false;
    if (!getInvokedMethodsList()
        .equals(other.getInvokedMethodsList())) return false;
    if (!getReferencedTypesList()
        .equals(other.getReferencedTypesList())) return false;
    if (hasPosition() != other.hasPosition()) return false;
    if (hasPosition()) {
      if (!getPosition()
          .equals(other.getPosition())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + STATIC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getStatic());
    hash = (37 * hash) + JS_ACCESSIBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getJsAccessible());
    if (getInvokedMethodsCount() > 0) {
      hash = (37 * hash) + INVOKED_METHODS_FIELD_NUMBER;
      hash = (53 * hash) + getInvokedMethodsList().hashCode();
    }
    if (getReferencedTypesCount() > 0) {
      hash = (37 * hash) + REFERENCED_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getReferencedTypesList().hashCode();
    }
    if (hasPosition()) {
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code j2cl.MemberInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:j2cl.MemberInfo)
      com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_MemberInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_MemberInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder.class);
    }

    // Construct using com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetInvokedMethodsFieldBuilder();
        internalGetPositionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      static_ = false;
      jsAccessible_ = false;
      if (invokedMethodsBuilder_ == null) {
        invokedMethods_ = java.util.Collections.emptyList();
      } else {
        invokedMethods_ = null;
        invokedMethodsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      referencedTypes_ = emptyIntList();
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_MemberInfo_descriptor;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo getDefaultInstanceForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo build() {
      com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo buildPartial() {
      com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo result = new com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo result) {
      if (invokedMethodsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          invokedMethods_ = java.util.Collections.unmodifiableList(invokedMethods_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.invokedMethods_ = invokedMethods_;
      } else {
        result.invokedMethods_ = invokedMethodsBuilder_.build();
      }
    }

    private void buildPartial0(com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.static_ = static_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.jsAccessible_ = jsAccessible_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        referencedTypes_.makeImmutable();
        result.referencedTypes_ = referencedTypes_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.position_ = positionBuilder_ == null
            ? position_
            : positionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo) {
        return mergeFrom((com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo other) {
      if (other == com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getStatic() != false) {
        setStatic(other.getStatic());
      }
      if (other.getJsAccessible() != false) {
        setJsAccessible(other.getJsAccessible());
      }
      if (invokedMethodsBuilder_ == null) {
        if (!other.invokedMethods_.isEmpty()) {
          if (invokedMethods_.isEmpty()) {
            invokedMethods_ = other.invokedMethods_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureInvokedMethodsIsMutable();
            invokedMethods_.addAll(other.invokedMethods_);
          }
          onChanged();
        }
      } else {
        if (!other.invokedMethods_.isEmpty()) {
          if (invokedMethodsBuilder_.isEmpty()) {
            invokedMethodsBuilder_.dispose();
            invokedMethodsBuilder_ = null;
            invokedMethods_ = other.invokedMethods_;
            bitField0_ = (bitField0_ & ~0x00000008);
            invokedMethodsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetInvokedMethodsFieldBuilder() : null;
          } else {
            invokedMethodsBuilder_.addAllMessages(other.invokedMethods_);
          }
        }
      }
      if (!other.referencedTypes_.isEmpty()) {
        if (referencedTypes_.isEmpty()) {
          referencedTypes_ = other.referencedTypes_;
          referencedTypes_.makeImmutable();
          bitField0_ |= 0x00000010;
        } else {
          ensureReferencedTypesIsMutable();
          referencedTypes_.addAll(other.referencedTypes_);
        }
        onChanged();
      }
      if (other.hasPosition()) {
        mergePosition(other.getPosition());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 24: {
              static_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 24
            case 32: {
              jsAccessible_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 32
            case 42: {
              com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation m =
                  input.readMessage(
                      com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.parser(),
                      extensionRegistry);
              if (invokedMethodsBuilder_ == null) {
                ensureInvokedMethodsIsMutable();
                invokedMethods_.add(m);
              } else {
                invokedMethodsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 48: {
              int v = input.readInt32();
              ensureReferencedTypesIsMutable();
              referencedTypes_.addInt(v);
              break;
            } // case 48
            case 50: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureReferencedTypesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                referencedTypes_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean static_ ;
    /**
     * <code>bool static = 3;</code>
     * @return The static.
     */
    @java.lang.Override
    public boolean getStatic() {
      return static_;
    }
    /**
     * <code>bool static = 3;</code>
     * @param value The static to set.
     * @return This builder for chaining.
     */
    public Builder setStatic(boolean value) {

      static_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool static = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatic() {
      bitField0_ = (bitField0_ & ~0x00000002);
      static_ = false;
      onChanged();
      return this;
    }

    private boolean jsAccessible_ ;
    /**
     * <code>bool js_accessible = 4;</code>
     * @return The jsAccessible.
     */
    @java.lang.Override
    public boolean getJsAccessible() {
      return jsAccessible_;
    }
    /**
     * <code>bool js_accessible = 4;</code>
     * @param value The jsAccessible to set.
     * @return This builder for chaining.
     */
    public Builder setJsAccessible(boolean value) {

      jsAccessible_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool js_accessible = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearJsAccessible() {
      bitField0_ = (bitField0_ & ~0x00000004);
      jsAccessible_ = false;
      onChanged();
      return this;
    }

    private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation> invokedMethods_ =
      java.util.Collections.emptyList();
    private void ensureInvokedMethodsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        invokedMethods_ = new java.util.ArrayList<com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation>(invokedMethods_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder> invokedMethodsBuilder_;

    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation> getInvokedMethodsList() {
      if (invokedMethodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invokedMethods_);
      } else {
        return invokedMethodsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public int getInvokedMethodsCount() {
      if (invokedMethodsBuilder_ == null) {
        return invokedMethods_.size();
      } else {
        return invokedMethodsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation getInvokedMethods(int index) {
      if (invokedMethodsBuilder_ == null) {
        return invokedMethods_.get(index);
      } else {
        return invokedMethodsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder setInvokedMethods(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation value) {
      if (invokedMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvokedMethodsIsMutable();
        invokedMethods_.set(index, value);
        onChanged();
      } else {
        invokedMethodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder setInvokedMethods(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder builderForValue) {
      if (invokedMethodsBuilder_ == null) {
        ensureInvokedMethodsIsMutable();
        invokedMethods_.set(index, builderForValue.build());
        onChanged();
      } else {
        invokedMethodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder addInvokedMethods(com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation value) {
      if (invokedMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvokedMethodsIsMutable();
        invokedMethods_.add(value);
        onChanged();
      } else {
        invokedMethodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder addInvokedMethods(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation value) {
      if (invokedMethodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvokedMethodsIsMutable();
        invokedMethods_.add(index, value);
        onChanged();
      } else {
        invokedMethodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder addInvokedMethods(
        com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder builderForValue) {
      if (invokedMethodsBuilder_ == null) {
        ensureInvokedMethodsIsMutable();
        invokedMethods_.add(builderForValue.build());
        onChanged();
      } else {
        invokedMethodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder addInvokedMethods(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder builderForValue) {
      if (invokedMethodsBuilder_ == null) {
        ensureInvokedMethodsIsMutable();
        invokedMethods_.add(index, builderForValue.build());
        onChanged();
      } else {
        invokedMethodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder addAllInvokedMethods(
        java.lang.Iterable<? extends com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation> values) {
      if (invokedMethodsBuilder_ == null) {
        ensureInvokedMethodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invokedMethods_);
        onChanged();
      } else {
        invokedMethodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder clearInvokedMethods() {
      if (invokedMethodsBuilder_ == null) {
        invokedMethods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        invokedMethodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public Builder removeInvokedMethods(int index) {
      if (invokedMethodsBuilder_ == null) {
        ensureInvokedMethodsIsMutable();
        invokedMethods_.remove(index);
        onChanged();
      } else {
        invokedMethodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder getInvokedMethodsBuilder(
        int index) {
      return internalGetInvokedMethodsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder getInvokedMethodsOrBuilder(
        int index) {
      if (invokedMethodsBuilder_ == null) {
        return invokedMethods_.get(index);  } else {
        return invokedMethodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder> 
         getInvokedMethodsOrBuilderList() {
      if (invokedMethodsBuilder_ != null) {
        return invokedMethodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invokedMethods_);
      }
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder addInvokedMethodsBuilder() {
      return internalGetInvokedMethodsFieldBuilder().addBuilder(
          com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder addInvokedMethodsBuilder(
        int index) {
      return internalGetInvokedMethodsFieldBuilder().addBuilder(
          index, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder> 
         getInvokedMethodsBuilderList() {
      return internalGetInvokedMethodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder> 
        internalGetInvokedMethodsFieldBuilder() {
      if (invokedMethodsBuilder_ == null) {
        invokedMethodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation.Builder, com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder>(
                invokedMethods_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        invokedMethods_ = null;
      }
      return invokedMethodsBuilder_;
    }

    private com.google.protobuf.Internal.IntList referencedTypes_ = emptyIntList();
    private void ensureReferencedTypesIsMutable() {
      if (!referencedTypes_.isModifiable()) {
        referencedTypes_ = makeMutableCopy(referencedTypes_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated int32 referenced_types = 6;</code>
     * @return A list containing the referencedTypes.
     */
    public java.util.List<java.lang.Integer>
        getReferencedTypesList() {
      referencedTypes_.makeImmutable();
      return referencedTypes_;
    }
    /**
     * <code>repeated int32 referenced_types = 6;</code>
     * @return The count of referencedTypes.
     */
    public int getReferencedTypesCount() {
      return referencedTypes_.size();
    }
    /**
     * <code>repeated int32 referenced_types = 6;</code>
     * @param index The index of the element to return.
     * @return The referencedTypes at the given index.
     */
    public int getReferencedTypes(int index) {
      return referencedTypes_.getInt(index);
    }
    /**
     * <code>repeated int32 referenced_types = 6;</code>
     * @param index The index to set the value at.
     * @param value The referencedTypes to set.
     * @return This builder for chaining.
     */
    public Builder setReferencedTypes(
        int index, int value) {

      ensureReferencedTypesIsMutable();
      referencedTypes_.setInt(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 referenced_types = 6;</code>
     * @param value The referencedTypes to add.
     * @return This builder for chaining.
     */
    public Builder addReferencedTypes(int value) {

      ensureReferencedTypesIsMutable();
      referencedTypes_.addInt(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 referenced_types = 6;</code>
     * @param values The referencedTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllReferencedTypes(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureReferencedTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, referencedTypes_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 referenced_types = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearReferencedTypes() {
      referencedTypes_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition position_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition, com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.Builder, com.google.j2cl.transpiler.backend.libraryinfo.SourcePositionOrBuilder> positionBuilder_;
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     * @return Whether the position field is set.
     */
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     * @return The position.
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition getPosition() {
      if (positionBuilder_ == null) {
        return position_ == null ? com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.getDefaultInstance() : position_;
      } else {
        return positionBuilder_.getMessage();
      }
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     */
    public Builder setPosition(com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition value) {
      if (positionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        position_ = value;
      } else {
        positionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     */
    public Builder setPosition(
        com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.Builder builderForValue) {
      if (positionBuilder_ == null) {
        position_ = builderForValue.build();
      } else {
        positionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     */
    public Builder mergePosition(com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition value) {
      if (positionBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          position_ != null &&
          position_ != com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.getDefaultInstance()) {
          getPositionBuilder().mergeFrom(value);
        } else {
          position_ = value;
        }
      } else {
        positionBuilder_.mergeFrom(value);
      }
      if (position_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     */
    public Builder clearPosition() {
      bitField0_ = (bitField0_ & ~0x00000020);
      position_ = null;
      if (positionBuilder_ != null) {
        positionBuilder_.dispose();
        positionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.Builder getPositionBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.SourcePositionOrBuilder getPositionOrBuilder() {
      if (positionBuilder_ != null) {
        return positionBuilder_.getMessageOrBuilder();
      } else {
        return position_ == null ?
            com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.getDefaultInstance() : position_;
      }
    }
    /**
     * <code>.j2cl.SourcePosition position = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition, com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.Builder, com.google.j2cl.transpiler.backend.libraryinfo.SourcePositionOrBuilder> 
        internalGetPositionFieldBuilder() {
      if (positionBuilder_ == null) {
        positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition, com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition.Builder, com.google.j2cl.transpiler.backend.libraryinfo.SourcePositionOrBuilder>(
                getPosition(),
                getParentForChildren(),
                isClean());
        position_ = null;
      }
      return positionBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:j2cl.MemberInfo)
  }

  // @@protoc_insertion_point(class_scope:j2cl.MemberInfo)
  private static final com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo();
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MemberInfo>
      PARSER = new com.google.protobuf.AbstractParser<MemberInfo>() {
    @java.lang.Override
    public MemberInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MemberInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MemberInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

