// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.libraryinfo;

@com.google.protobuf.Generated
public interface MemberInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.MemberInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool static = 3;</code>
   * @return The static.
   */
  boolean getStatic();

  /**
   * <code>bool js_accessible = 4;</code>
   * @return The jsAccessible.
   */
  boolean getJsAccessible();

  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation> 
      getInvokedMethodsList();
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocation getInvokedMethods(int index);
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  int getInvokedMethodsCount();
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder> 
      getInvokedMethodsOrBuilderList();
  /**
   * <code>repeated .j2cl.MethodInvocation invoked_methods = 5;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.MethodInvocationOrBuilder getInvokedMethodsOrBuilder(
      int index);

  /**
   * <code>repeated int32 referenced_types = 6;</code>
   * @return A list containing the referencedTypes.
   */
  java.util.List<java.lang.Integer> getReferencedTypesList();
  /**
   * <code>repeated int32 referenced_types = 6;</code>
   * @return The count of referencedTypes.
   */
  int getReferencedTypesCount();
  /**
   * <code>repeated int32 referenced_types = 6;</code>
   * @param index The index of the element to return.
   * @return The referencedTypes at the given index.
   */
  int getReferencedTypes(int index);

  /**
   * <code>.j2cl.SourcePosition position = 7;</code>
   * @return Whether the position field is set.
   */
  boolean hasPosition();
  /**
   * <code>.j2cl.SourcePosition position = 7;</code>
   * @return The position.
   */
  com.google.j2cl.transpiler.backend.libraryinfo.SourcePosition getPosition();
  /**
   * <code>.j2cl.SourcePosition position = 7;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.SourcePositionOrBuilder getPositionOrBuilder();
}
