// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto

package com.google.j2cl.transpiler.backend.libraryinfo;

public interface SourcePositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.SourcePosition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 start = 1;</code>
   * @return The start.
   */
  int getStart();

  /**
   * <code>int32 end = 2;</code>
   * @return The end.
   */
  int getEnd();
}
