// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto
// Protobuf Java Version: 4.31.0

package com.google.j2cl.transpiler.backend.libraryinfo;

/**
 * Protobuf type {@code j2cl.TypeInfo}
 */
@com.google.protobuf.Generated
public final class TypeInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:j2cl.TypeInfo)
    TypeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 0,
      /* suffix= */ "",
      TypeInfo.class.getName());
  }
  // Use TypeInfo.newBuilder() to construct.
  private TypeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TypeInfo() {
    implementsTypes_ = emptyIntList();
    members_ = java.util.Collections.emptyList();
    headerSourceFilePath_ = "";
    implSourceFilePath_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_TypeInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_TypeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder.class);
  }

  public static final int TYPE_ID_FIELD_NUMBER = 1;
  private int typeId_ = 0;
  /**
   * <code>int32 type_id = 1;</code>
   * @return The typeId.
   */
  @java.lang.Override
  public int getTypeId() {
    return typeId_;
  }

  public static final int EXTENDS_TYPE_FIELD_NUMBER = 2;
  private int extendsType_ = 0;
  /**
   * <code>int32 extends_type = 2;</code>
   * @return The extendsType.
   */
  @java.lang.Override
  public int getExtendsType() {
    return extendsType_;
  }

  public static final int IMPLEMENTS_TYPES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList implementsTypes_ =
      emptyIntList();
  /**
   * <code>repeated int32 implements_types = 3;</code>
   * @return A list containing the implementsTypes.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getImplementsTypesList() {
    return implementsTypes_;
  }
  /**
   * <code>repeated int32 implements_types = 3;</code>
   * @return The count of implementsTypes.
   */
  public int getImplementsTypesCount() {
    return implementsTypes_.size();
  }
  /**
   * <code>repeated int32 implements_types = 3;</code>
   * @param index The index of the element to return.
   * @return The implementsTypes at the given index.
   */
  public int getImplementsTypes(int index) {
    return implementsTypes_.getInt(index);
  }
  private int implementsTypesMemoizedSerializedSize = -1;

  public static final int MEMBERS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo> members_;
  /**
   * <code>repeated .j2cl.MemberInfo members = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo> getMembersList() {
    return members_;
  }
  /**
   * <code>repeated .j2cl.MemberInfo members = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder> 
      getMembersOrBuilderList() {
    return members_;
  }
  /**
   * <code>repeated .j2cl.MemberInfo members = 4;</code>
   */
  @java.lang.Override
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated .j2cl.MemberInfo members = 4;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo getMembers(int index) {
    return members_.get(index);
  }
  /**
   * <code>repeated .j2cl.MemberInfo members = 4;</code>
   */
  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder getMembersOrBuilder(
      int index) {
    return members_.get(index);
  }

  public static final int HEADER_SOURCE_FILE_PATH_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object headerSourceFilePath_ = "";
  /**
   * <code>string header_source_file_path = 5;</code>
   * @return The headerSourceFilePath.
   */
  @java.lang.Override
  public java.lang.String getHeaderSourceFilePath() {
    java.lang.Object ref = headerSourceFilePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      headerSourceFilePath_ = s;
      return s;
    }
  }
  /**
   * <code>string header_source_file_path = 5;</code>
   * @return The bytes for headerSourceFilePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHeaderSourceFilePathBytes() {
    java.lang.Object ref = headerSourceFilePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      headerSourceFilePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMPL_SOURCE_FILE_PATH_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object implSourceFilePath_ = "";
  /**
   * <code>string impl_source_file_path = 6;</code>
   * @return The implSourceFilePath.
   */
  @java.lang.Override
  public java.lang.String getImplSourceFilePath() {
    java.lang.Object ref = implSourceFilePath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      implSourceFilePath_ = s;
      return s;
    }
  }
  /**
   * <code>string impl_source_file_path = 6;</code>
   * @return The bytes for implSourceFilePath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImplSourceFilePathBytes() {
    java.lang.Object ref = implSourceFilePath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      implSourceFilePath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JSTYPE_INTERFACE_FIELD_NUMBER = 7;
  private boolean jstypeInterface_ = false;
  /**
   * <code>bool jstype_interface = 7;</code>
   * @return The jstypeInterface.
   */
  @java.lang.Override
  public boolean getJstypeInterface() {
    return jstypeInterface_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (typeId_ != 0) {
      output.writeInt32(1, typeId_);
    }
    if (extendsType_ != 0) {
      output.writeInt32(2, extendsType_);
    }
    if (getImplementsTypesList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(implementsTypesMemoizedSerializedSize);
    }
    for (int i = 0; i < implementsTypes_.size(); i++) {
      output.writeInt32NoTag(implementsTypes_.getInt(i));
    }
    for (int i = 0; i < members_.size(); i++) {
      output.writeMessage(4, members_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(headerSourceFilePath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, headerSourceFilePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(implSourceFilePath_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, implSourceFilePath_);
    }
    if (jstypeInterface_ != false) {
      output.writeBool(7, jstypeInterface_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (typeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, typeId_);
    }
    if (extendsType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, extendsType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < implementsTypes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(implementsTypes_.getInt(i));
      }
      size += dataSize;
      if (!getImplementsTypesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      implementsTypesMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < members_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, members_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(headerSourceFilePath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, headerSourceFilePath_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(implSourceFilePath_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, implSourceFilePath_);
    }
    if (jstypeInterface_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, jstypeInterface_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo)) {
      return super.equals(obj);
    }
    com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo other = (com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo) obj;

    if (getTypeId()
        != other.getTypeId()) return false;
    if (getExtendsType()
        != other.getExtendsType()) return false;
    if (!getImplementsTypesList()
        .equals(other.getImplementsTypesList())) return false;
    if (!getMembersList()
        .equals(other.getMembersList())) return false;
    if (!getHeaderSourceFilePath()
        .equals(other.getHeaderSourceFilePath())) return false;
    if (!getImplSourceFilePath()
        .equals(other.getImplSourceFilePath())) return false;
    if (getJstypeInterface()
        != other.getJstypeInterface()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTypeId();
    hash = (37 * hash) + EXTENDS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getExtendsType();
    if (getImplementsTypesCount() > 0) {
      hash = (37 * hash) + IMPLEMENTS_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getImplementsTypesList().hashCode();
    }
    if (getMembersCount() > 0) {
      hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getMembersList().hashCode();
    }
    hash = (37 * hash) + HEADER_SOURCE_FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getHeaderSourceFilePath().hashCode();
    hash = (37 * hash) + IMPL_SOURCE_FILE_PATH_FIELD_NUMBER;
    hash = (53 * hash) + getImplSourceFilePath().hashCode();
    hash = (37 * hash) + JSTYPE_INTERFACE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getJstypeInterface());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code j2cl.TypeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:j2cl.TypeInfo)
      com.google.j2cl.transpiler.backend.libraryinfo.TypeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_TypeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_TypeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.class, com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.Builder.class);
    }

    // Construct using com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      typeId_ = 0;
      extendsType_ = 0;
      implementsTypes_ = emptyIntList();
      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
      } else {
        members_ = null;
        membersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      headerSourceFilePath_ = "";
      implSourceFilePath_ = "";
      jstypeInterface_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.LibraryInfoOuterClass.internal_static_j2cl_TypeInfo_descriptor;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getDefaultInstanceForType() {
      return com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo build() {
      com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo buildPartial() {
      com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo result = new com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo result) {
      if (membersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          members_ = java.util.Collections.unmodifiableList(members_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.members_ = members_;
      } else {
        result.members_ = membersBuilder_.build();
      }
    }

    private void buildPartial0(com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.typeId_ = typeId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.extendsType_ = extendsType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        implementsTypes_.makeImmutable();
        result.implementsTypes_ = implementsTypes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.headerSourceFilePath_ = headerSourceFilePath_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.implSourceFilePath_ = implSourceFilePath_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.jstypeInterface_ = jstypeInterface_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo) {
        return mergeFrom((com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo other) {
      if (other == com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo.getDefaultInstance()) return this;
      if (other.getTypeId() != 0) {
        setTypeId(other.getTypeId());
      }
      if (other.getExtendsType() != 0) {
        setExtendsType(other.getExtendsType());
      }
      if (!other.implementsTypes_.isEmpty()) {
        if (implementsTypes_.isEmpty()) {
          implementsTypes_ = other.implementsTypes_;
          implementsTypes_.makeImmutable();
          bitField0_ |= 0x00000004;
        } else {
          ensureImplementsTypesIsMutable();
          implementsTypes_.addAll(other.implementsTypes_);
        }
        onChanged();
      }
      if (membersBuilder_ == null) {
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
      } else {
        if (!other.members_.isEmpty()) {
          if (membersBuilder_.isEmpty()) {
            membersBuilder_.dispose();
            membersBuilder_ = null;
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000008);
            membersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetMembersFieldBuilder() : null;
          } else {
            membersBuilder_.addAllMessages(other.members_);
          }
        }
      }
      if (!other.getHeaderSourceFilePath().isEmpty()) {
        headerSourceFilePath_ = other.headerSourceFilePath_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getImplSourceFilePath().isEmpty()) {
        implSourceFilePath_ = other.implSourceFilePath_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getJstypeInterface() != false) {
        setJstypeInterface(other.getJstypeInterface());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              typeId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              extendsType_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              int v = input.readInt32();
              ensureImplementsTypesIsMutable();
              implementsTypes_.addInt(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureImplementsTypesIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                implementsTypes_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 34: {
              com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo m =
                  input.readMessage(
                      com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.parser(),
                      extensionRegistry);
              if (membersBuilder_ == null) {
                ensureMembersIsMutable();
                members_.add(m);
              } else {
                membersBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              headerSourceFilePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              implSourceFilePath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              jstypeInterface_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int typeId_ ;
    /**
     * <code>int32 type_id = 1;</code>
     * @return The typeId.
     */
    @java.lang.Override
    public int getTypeId() {
      return typeId_;
    }
    /**
     * <code>int32 type_id = 1;</code>
     * @param value The typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeId(int value) {

      typeId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      typeId_ = 0;
      onChanged();
      return this;
    }

    private int extendsType_ ;
    /**
     * <code>int32 extends_type = 2;</code>
     * @return The extendsType.
     */
    @java.lang.Override
    public int getExtendsType() {
      return extendsType_;
    }
    /**
     * <code>int32 extends_type = 2;</code>
     * @param value The extendsType to set.
     * @return This builder for chaining.
     */
    public Builder setExtendsType(int value) {

      extendsType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 extends_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtendsType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      extendsType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.IntList implementsTypes_ = emptyIntList();
    private void ensureImplementsTypesIsMutable() {
      if (!implementsTypes_.isModifiable()) {
        implementsTypes_ = makeMutableCopy(implementsTypes_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated int32 implements_types = 3;</code>
     * @return A list containing the implementsTypes.
     */
    public java.util.List<java.lang.Integer>
        getImplementsTypesList() {
      implementsTypes_.makeImmutable();
      return implementsTypes_;
    }
    /**
     * <code>repeated int32 implements_types = 3;</code>
     * @return The count of implementsTypes.
     */
    public int getImplementsTypesCount() {
      return implementsTypes_.size();
    }
    /**
     * <code>repeated int32 implements_types = 3;</code>
     * @param index The index of the element to return.
     * @return The implementsTypes at the given index.
     */
    public int getImplementsTypes(int index) {
      return implementsTypes_.getInt(index);
    }
    /**
     * <code>repeated int32 implements_types = 3;</code>
     * @param index The index to set the value at.
     * @param value The implementsTypes to set.
     * @return This builder for chaining.
     */
    public Builder setImplementsTypes(
        int index, int value) {

      ensureImplementsTypesIsMutable();
      implementsTypes_.setInt(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 implements_types = 3;</code>
     * @param value The implementsTypes to add.
     * @return This builder for chaining.
     */
    public Builder addImplementsTypes(int value) {

      ensureImplementsTypesIsMutable();
      implementsTypes_.addInt(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 implements_types = 3;</code>
     * @param values The implementsTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllImplementsTypes(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureImplementsTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, implementsTypes_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 implements_types = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplementsTypes() {
      implementsTypes_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo> members_ =
      java.util.Collections.emptyList();
    private void ensureMembersIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        members_ = new java.util.ArrayList<com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo>(members_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder> membersBuilder_;

    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo> getMembersList() {
      if (membersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(members_);
      } else {
        return membersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public int getMembersCount() {
      if (membersBuilder_ == null) {
        return members_.size();
      } else {
        return membersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo getMembers(int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);
      } else {
        return membersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder setMembers(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
      } else {
        membersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder setMembers(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.set(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder addMembers(com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
      } else {
        membersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder addMembers(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo value) {
      if (membersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembersIsMutable();
        members_.add(index, value);
        onChanged();
      } else {
        membersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder addMembers(
        com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder addMembers(
        int index, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder builderForValue) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.add(index, builderForValue.build());
        onChanged();
      } else {
        membersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder addAllMembers(
        java.lang.Iterable<? extends com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo> values) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
      } else {
        membersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder clearMembers() {
      if (membersBuilder_ == null) {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        membersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public Builder removeMembers(int index) {
      if (membersBuilder_ == null) {
        ensureMembersIsMutable();
        members_.remove(index);
        onChanged();
      } else {
        membersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder getMembersBuilder(
        int index) {
      return internalGetMembersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder getMembersOrBuilder(
        int index) {
      if (membersBuilder_ == null) {
        return members_.get(index);  } else {
        return membersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder> 
         getMembersOrBuilderList() {
      if (membersBuilder_ != null) {
        return membersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(members_);
      }
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder addMembersBuilder() {
      return internalGetMembersFieldBuilder().addBuilder(
          com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder addMembersBuilder(
        int index) {
      return internalGetMembersFieldBuilder().addBuilder(
          index, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .j2cl.MemberInfo members = 4;</code>
     */
    public java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder> 
         getMembersBuilderList() {
      return internalGetMembersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder> 
        internalGetMembersFieldBuilder() {
      if (membersBuilder_ == null) {
        membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo.Builder, com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder>(
                members_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        members_ = null;
      }
      return membersBuilder_;
    }

    private java.lang.Object headerSourceFilePath_ = "";
    /**
     * <code>string header_source_file_path = 5;</code>
     * @return The headerSourceFilePath.
     */
    public java.lang.String getHeaderSourceFilePath() {
      java.lang.Object ref = headerSourceFilePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headerSourceFilePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string header_source_file_path = 5;</code>
     * @return The bytes for headerSourceFilePath.
     */
    public com.google.protobuf.ByteString
        getHeaderSourceFilePathBytes() {
      java.lang.Object ref = headerSourceFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerSourceFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string header_source_file_path = 5;</code>
     * @param value The headerSourceFilePath to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderSourceFilePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      headerSourceFilePath_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string header_source_file_path = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeaderSourceFilePath() {
      headerSourceFilePath_ = getDefaultInstance().getHeaderSourceFilePath();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string header_source_file_path = 5;</code>
     * @param value The bytes for headerSourceFilePath to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderSourceFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      headerSourceFilePath_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object implSourceFilePath_ = "";
    /**
     * <code>string impl_source_file_path = 6;</code>
     * @return The implSourceFilePath.
     */
    public java.lang.String getImplSourceFilePath() {
      java.lang.Object ref = implSourceFilePath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        implSourceFilePath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string impl_source_file_path = 6;</code>
     * @return The bytes for implSourceFilePath.
     */
    public com.google.protobuf.ByteString
        getImplSourceFilePathBytes() {
      java.lang.Object ref = implSourceFilePath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        implSourceFilePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string impl_source_file_path = 6;</code>
     * @param value The implSourceFilePath to set.
     * @return This builder for chaining.
     */
    public Builder setImplSourceFilePath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      implSourceFilePath_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string impl_source_file_path = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplSourceFilePath() {
      implSourceFilePath_ = getDefaultInstance().getImplSourceFilePath();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string impl_source_file_path = 6;</code>
     * @param value The bytes for implSourceFilePath to set.
     * @return This builder for chaining.
     */
    public Builder setImplSourceFilePathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      implSourceFilePath_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private boolean jstypeInterface_ ;
    /**
     * <code>bool jstype_interface = 7;</code>
     * @return The jstypeInterface.
     */
    @java.lang.Override
    public boolean getJstypeInterface() {
      return jstypeInterface_;
    }
    /**
     * <code>bool jstype_interface = 7;</code>
     * @param value The jstypeInterface to set.
     * @return This builder for chaining.
     */
    public Builder setJstypeInterface(boolean value) {

      jstypeInterface_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool jstype_interface = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearJstypeInterface() {
      bitField0_ = (bitField0_ & ~0x00000040);
      jstypeInterface_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:j2cl.TypeInfo)
  }

  // @@protoc_insertion_point(class_scope:j2cl.TypeInfo)
  private static final com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo();
  }

  public static com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TypeInfo>
      PARSER = new com.google.protobuf.AbstractParser<TypeInfo>() {
    @java.lang.Override
    public TypeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TypeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TypeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.j2cl.transpiler.backend.libraryinfo.TypeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

