// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transpiler/java/com/google/j2cl/transpiler/backend/libraryinfo/library_info.proto

package com.google.j2cl.transpiler.backend.libraryinfo;

public interface TypeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:j2cl.TypeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 type_id = 1;</code>
   * @return The typeId.
   */
  int getTypeId();

  /**
   * <code>int32 extends_type = 2;</code>
   * @return The extendsType.
   */
  int getExtendsType();

  /**
   * <code>repeated int32 implements_type = 3;</code>
   * @return A list containing the implementsType.
   */
  java.util.List<java.lang.Integer> getImplementsTypeList();
  /**
   * <code>repeated int32 implements_type = 3;</code>
   * @return The count of implementsType.
   */
  int getImplementsTypeCount();
  /**
   * <code>repeated int32 implements_type = 3;</code>
   * @param index The index of the element to return.
   * @return The implementsType at the given index.
   */
  int getImplementsType(int index);

  /**
   * <code>repeated .j2cl.MemberInfo member = 4;</code>
   */
  java.util.List<com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo> 
      getMemberList();
  /**
   * <code>repeated .j2cl.MemberInfo member = 4;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.MemberInfo getMember(int index);
  /**
   * <code>repeated .j2cl.MemberInfo member = 4;</code>
   */
  int getMemberCount();
  /**
   * <code>repeated .j2cl.MemberInfo member = 4;</code>
   */
  java.util.List<? extends com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder> 
      getMemberOrBuilderList();
  /**
   * <code>repeated .j2cl.MemberInfo member = 4;</code>
   */
  com.google.j2cl.transpiler.backend.libraryinfo.MemberInfoOrBuilder getMemberOrBuilder(
      int index);

  /**
   * <code>string header_source_file_path = 5;</code>
   * @return The headerSourceFilePath.
   */
  java.lang.String getHeaderSourceFilePath();
  /**
   * <code>string header_source_file_path = 5;</code>
   * @return The bytes for headerSourceFilePath.
   */
  com.google.protobuf.ByteString
      getHeaderSourceFilePathBytes();

  /**
   * <code>string impl_source_file_path = 6;</code>
   * @return The implSourceFilePath.
   */
  java.lang.String getImplSourceFilePath();
  /**
   * <code>string impl_source_file_path = 6;</code>
   * @return The bytes for implSourceFilePath.
   */
  com.google.protobuf.ByteString
      getImplSourceFilePathBytes();

  /**
   * <code>bool jstype_interface = 7;</code>
   * @return The jstypeInterface.
   */
  boolean getJstypeInterface();
}
