package elemental2.dom;
import elemental2.dom.HTMLFormElement;
import org.jspecify.annotations.Nullable;
import elemental2.dom.ValidityState;
import elemental2.dom.HTMLElement;
import elemental2.dom.NodeList;
import elemental2.dom.HTMLLabelElement;
import java.lang.String;
import jsinterop.annotations.JsType;
import jsinterop.annotations.JsPackage;
@JsType(isNative = true,namespace = JsPackage.GLOBAL)
public class HTMLTextAreaElement extends HTMLElement{
public String accessKey;
public boolean autofocus;
public int cols;
public String defaultValue;
public String dirName;
public boolean disabled;
public @Nullable HTMLFormElement form;
public @Nullable NodeList<HTMLLabelElement> labels;
public int maxLength;
public int minLength;
public String name;
public String placeholder;
public boolean readOnly;
public int rows;
public double selectionEnd;
public double selectionStart;
public int tabIndex;
public int textLength;
public String type;
public String validationMessage;
public @Nullable ValidityState validity;
public String value;
public boolean willValidate;
public String wrap;
public native void blur();
public native boolean checkValidity();
public native void focus();
public native boolean reportValidity();
public native void select();
public native void setCustomValidity(String message);
public native void setRangeText(String replacement,double start,double end,String selectionMode);
public native void setRangeText(String replacement,double start,double end);
public native void setRangeText(String replacement,double start);
public native void setRangeText(String replacement);
public native void setSelectionRange(double selectionStart,double selectionEnd);
}
