package elemental2.dom;
import elemental2.dom.HTMLFormElement;
import org.jspecify.annotations.Nullable;
import elemental2.dom.ValidityState;
import elemental2.dom.HTMLOptionElement;
import elemental2.dom.HTMLCollection;
import elemental2.dom.HTMLLabelElement;
import elemental2.dom.HTMLOptionsCollection;
import elemental2.dom.HTMLElement;
import elemental2.dom.NodeList;
import java.lang.String;
import jsinterop.annotations.JsType;
import jsinterop.annotations.JsPackage;
@JsType(isNative = true,namespace = JsPackage.GLOBAL)
public class HTMLSelectElement extends HTMLElement{
public boolean autofocus;
public boolean disabled;
public @Nullable HTMLFormElement form;
public @Nullable NodeList<HTMLLabelElement> labels;
public int length;
public boolean multiple;
public String name;
public HTMLOptionsCollection options;
public boolean required;
public int selectedIndex;
public @Nullable HTMLCollection<HTMLOptionElement> selectedOptions;
public int size;
public String type;
public String validationMessage;
public @Nullable ValidityState validity;
public String value;
public boolean willValidate;
public native void add(@Nullable HTMLElement element,@Nullable HTMLElement before);
public native void add(@Nullable HTMLElement element);
public native void blur();
public native boolean checkValidity();
public native void focus();
public native void remove();
public native void remove(int index);
public native boolean reportValidity();
public native void setCustomValidity(String message);
}
